//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"os"
	"os/exec"
	"time"
)

func main() {
	// Get build date
	buildDate := time.Now().Format(time.RFC3339)

	// Get git commit hash
	commitHash := "unknown"
	cmd := exec.Command("git", "rev-parse", "HEAD")
	if output, err := cmd.Output(); err == nil {
		commitHash = string(output[:len(output)-1]) // Remove trailing newline
	}

	// Generate build_info.go
	content := fmt.Sprintf(`package main

// This file is auto-generated by go generate. Do not edit.

// Build information
const (
	BuildDate  = %q
	CommitHash = %q
)
`, buildDate, commitHash)

	if err := os.WriteFile("build_info.go", []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing build_info.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Generated build_info.go")
}
